version: 2.0
jobs:
  test:
    docker:
      - image: circleci/android:api-28-ndk-r17b
    steps:
      - checkout
      - run: ./gradlew :sample:assembleDebug

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
